export const PlanetData = {
  mercury: {
    name: "mercury",
    info: "Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets. Mercury is one of four terrestrial planets in the Solar System, and is a rocky body like Earth.",
    fullimg: "../assets/planet-mercury.svg",
    internal: "../assets/planet-mercury-internal.svg",
    geology: "../assets/geology-earth.png",
    color: "#419EBB",
    rotation: "58.6 DAYS",
    revo: "87.97 DAYS",
    radius: 2439.7,
    temp: 430,
  },
  earth: {
    name: "earth",
    info: "Third planet from the Sun and the only known planet to harbor life. About 29.2% of Earth's surface is land with remaining 70.8% is covered with water. Earth's distance from the Sun, physical properties and geological history have allowed life to evolve and thrive.",
    fullimg: "../assets/planet-earth.svg",
    internal: "../assets/planet-earth-internal.svg",
    geology: "../assets/geology-earth.png",
    color: "#6D2ED5",
    rotation: "0.99 DAYS",
    revo: "365,26 DAYS",
    radius: 6371,
    temp: 16,
  },
  venus: {
    name: "venus",
    info: "Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth's night sky after the Moon, Venus can cast shadows and can be, on rare occasions, visible to the naked eye in broad daylight.",
    fullimg: "../assets/planet-venus.svg",
    internal: "../assets/planet-venus-internal.svg",
    geology: "../assets/geology-venus.png",
    color: "#EDA249",
    rotation: "243 DAYS",
    revo: "224.76 DAYS",
    radius: 6051.8,
    temp: 471,
  },
  mars: {
    name: "mars",
    info: "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In English, Mars carries the name of the Roman god of war and is often referred to as the 'Red Planet'.",
    fullimg: "../assets/planet-mars.svg",
    internal: "../assets/planet-mars-internal.svg",
    geology: "../assets/geology-mars.png",
    color: "#D14C32",
    rotation: "1.03 DAYS",
    revo: "1.88 YEARS",
    radius: 3389.5,
    temp: -28,
  },
  jupiter: {
    name: "jupiter",
    info: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass two and a half times that of all the other planets in the Solar System combined, but less than one-thousandth the mass of the Sun.",
    fullimg: "../assets/planet-jupiter.svg",
    internal: "../assets/planet-jupiter-internal.svg",
    geology: "../assets/geology-jupiter.png",
    color: "#D83A34",
    rotation: "9.93 hours",
    revo: "11.86 YEARS",
    radius: 69911,
    temp: -108,
  },
  saturn: {
    name: "saturn",
    info: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth. It only has one-eighth the average density of Earth.",
    fullimg: "../assets/planet-saturn.svg",
    internal: "../assets/planet-saturn-internal.svg",
    geology: "../assets/geology-saturn.png",
    color: "#CD5120",
    rotation: "10.8 hours",
    revo: "29.46 YEARS",
    radius: 58232,
    temp: -138,
  },
  uranus: {
    name: "uranus",
    info: "Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus according to Greek mythology, was the great-grandfather of Ares. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.",
    fullimg: "../assets/planet-uranus.svg",
    internal: "../assets/planet-uranus-internal.svg",
    geology: "../assets/geology-uranus.png",
    color: "#1EC1A2",
    rotation: "17.2 hours",
    revo: "84 YEARS",
    radius: 25362,
    temp: -195,
  },
  neptune: {
    name: "neptune",
    info: "Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, more massive than its near-twin Uranus..",
    fullimg: "../assets/planet-neptune.svg",
    internal: "../assets/planet-neptune-internal.svg",
    geology: "../assets/geology-neptune.png",
    color: "#2D68F0",
    rotation: "16.08 hours",
    revo: "164.79 YEARS",
    radius: 24662,
    temp: -201,
  },
};
